### ISSUE TITLE
Where did this come from, and how did it get on my PC?

### ISSUE THREAD

**Issue by StrikerMan780** [djpnewton/vmulti#24]
For some reason, "VMultia HID" has started showing in my game controllers list, and it's been screwing with my controller-supportinggames. I don't know WHAT installed it, or how it got there.

A google search brought me here. What I want to know most of all, is how to get rid of it.

EDIT: Seems it came from TouchMote. Seems to not disable the driver while not in use.

**Comment by darealdoomer** [comment]
Thanks. I had a fistful of my hair ready to pull out, but you provided the answer!

**Comment by djpnewton** [comment]
You should be able to delete the VMulti device using Windows Device Manager.

If there are problems deleting it try "View->Devices By Connection" and first disable the child devices of VMulti before deleting it.

**Comment by EK9Hatch** [comment]
Thank you SOO MUCH, I literally NEVER would have found this out unless you told me and im using the 6+R BEAN H Shifter on youtube and this literally FIXED IT beacuse it wasnt detecting it but now it is, If it wasn't for this thread i never would have got an answer THANK YOU INTERNET!!!
