### ISSUE TITLE
How to send a mouse left button click(down and up) to HID?

### ISSUE THREAD

**Issue by BruceMok** [djpnewton/vmulti#31]
The "testvmulti.c" show us how to move mouse, but i have no idea to send mouse button event.

`        case REPORTID_MOUSE:
            //
            // Send the mouse report
            //
            printf("Sending mouse report\n"); 
            //vmulti_update_mouse(vmulti, 0, 1000, 10000, 0);
            vmulti_update_mouse(vmulti, MOUSE_BUTTON_1, 18500, 18000, 0);
            break;
`
I'm trying to do like this, but not worked.

**Comment by djpnewton** [comment]
The desktop input process might be a bit sensitive to how you send it events. You can try emulating how an actual hardware mouse might send events:

eg:
``` c
vmulti_update_mouse(vmulti, 0, 18500, 18000, 0); // move to location
Sleep(10);
vmulti_update_mouse(vmulti, MOUSE_BUTTON_1, 18500, 18000, 0); // press mouse button
Sleep(10);
vmulti_update_mouse(vmulti, 0, 18500, 18000, 0); // unpress mouse button
```

**Comment by BruceMok** [comment]
It works! thanks very much.
