### ISSUE TITLE
how to scroll 1 pixel

### ISSUE THREAD

**Issue by sleepinging** [djpnewton/vmulti#32]
can i use vmulti to scroll 1 pixel like using touch pad? i can use SendInput simulate the operator ,but if i use vmulti , it at least scroll 120 pixel

**Comment by ihor-drachuk** [comment]
I'm not the author, but seems '120 pixels' is an OS-specific behavior when it receives one wheel-scroll event from HID device (in simple terms). And probably this value can be adjusted in settings, but it is unlikely that it could be 1 pixel and unlikely this can be changed from vmulti driver.

**Comment by djpnewton** [comment]
yes I think ihor is most likely correct
