### ISSUE TITLE
a relative mouse problem

### ISSUE THREAD

**Issue by ctinkong** [djpnewton/vmulti#33]
Hi, i was using vmulti on my remote desktop app. and when i used api <**vmulti_update_relative_mouse**> to move mouse position relatively(like x-axis move 10 pixels), the actual movement is greater than 10 pixels. is that a bug or that's the design? thanks.

![动画](https://user-images.githubusercontent.com/50896989/124141906-5d5cc600-dabc-11eb-8290-2bb4389ffc96.gif)

**Comment by ihor-drachuk** [comment]
Hi! I assume OS affects **cursor** movement. So, cursor movements are affected by mouse movement (even vmulti) + system settings. Did you try to change mouse move speed in system settings? Does it affect your test?

**Comment by ctinkong** [comment]
@ihor-drachuk when I turn off enhanced pointer precision and set the mouse move speed to normal, it works well. thanks.
